/*
 * Helper class to define database connection information
 */
package edu.depaul.se.account.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 */
public class HSQLDBMemDriverHelper {

    private static final String CONNECTION_URL = "jdbc:hsqldb:mem:.";
    private static final String USER_NAME = "sa";
    private static final String PASSWORD = "";

        /**
     * @throws java.lang.Exception
     */
    static {
        try {
            Class.forName("org.hsqldb.jdbcDriver");
        } catch (ClassNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }
    
    /**
     *
     * @return connection based on in memory database for HSQLDB
     * @throws SQLException
     */
    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(CONNECTION_URL, USER_NAME, PASSWORD);
    }
    
    public static void setupTable() {
        try (Connection connection = getConnection()) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("create table accounts(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY, name varchar(50), balance float)");
                statement.executeUpdate("insert into accounts(name, balance) values ('Paul', 100)");
                statement.executeUpdate("insert into accounts(name, balance) values ('John', 100)");
                statement.executeUpdate("insert into accounts(name, balance) values ('George', 100)");
                statement.executeUpdate("insert into accounts(name, balance) values ('Ringo', 100)");
            } catch (SQLException ex) {
                Logger.getLogger(HSQLDBMemDriverHelper.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HSQLDBMemDriverHelper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void removeTable() {
        try (Connection connection = getConnection();
                Statement statement = connection.createStatement();) {
            statement.execute("drop table accounts");
        } catch (SQLException sql) {
            System.out.println(sql.toString());
        }
    }    
}
